### ISSUE TITLE
Slow down when editing

### ISSUE THREAD

**Issue by andrerjesus** [geopython/CadTools#20]
I have two machines with QGIS 2.8.3 LTS and CadTools 0.6.3 with big slows down when enabling/disabling editing or saving changes with the plugin enabled. Usually that happens after 30-60 minutos after de file is open. It doesn't matter if It is a database connection (MSSQL) or shapefile/memory layer.

**Comment by wiltomap** [comment]
I have exactly the same issue, running QGIS 2.14.11 LTR! I have to close and re-start QGIS in order to get normal behaviour back. Layers can be very small shapefiles with less than 10 features.

**Comment by victorkourtelis** [comment]
This is due to an erroneous pattern in the code: the same slot function (toggle) is connected with both the "editing started" / "editing stopped" signal and the "current layer changed" signal without preceded disconnection.

The [proposed pull request](https://github.com/geopython/CadTools/pull/28) fixes the issue as it was addressed in Digitizing Tools, too.

**Comment by victorkourtelis** [comment]
Shouldn't the new version be uploaded to [QGIS Repository](
http://plugins.qgis.org/plugins/cadtools/), too?

**Comment by kalxas** [comment]
There is no automatic link between new commits and new version on qgis.org, it is usually decided ad hoc.
